import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
import { state } from '../src/config.js';

const entries = new Map();
const storage = { get length() { return entries.size; }, key: index => [...entries.keys()][index], getItem: key => entries.get(key) ?? null, setItem: (key, value) => entries.set(key, value), removeItem: key => entries.delete(key) };
const listeners = new Map();
const window = { localStorage: storage, addEventListener: (name, fn) => listeners.set(name, fn), removeEventListener: name => listeners.delete(name) };
const document = { hidden: false, addEventListener: window.addEventListener, removeEventListener: window.removeEventListener };
const context = vm.createContext({ window, document });
let user = { id: 'admin-one' }, record, fetch;
const noop = () => {};
const api = { getStoredUser: () => user, recordDemoRound: (...args) => record(...args), fetchLobby: (...args) => fetch(...args), clearSession: noop, confirmSandboxDeposit: noop, createDepositIntent: noop, requestWithdrawal: noop };
function synthetic(exports) { return new vm.SyntheticModule(Object.keys(exports), function () { for (const [key, value] of Object.entries(exports)) this.setExport(key, value); }, { context }); }
const apiModule = synthetic(api);
const history = new vm.SourceTextModule(await readFile(new URL('../src/services/demoHistory.js', import.meta.url), 'utf8'), { context });
await history.link(() => apiModule);
await history.evaluate();
const { queueDemoResult, flushDemoHistory } = history.namespace;
const deferred = () => { let resolve, reject; const promise = new Promise((yes, no) => { resolve = yes; reject = no; }); return { resolve, reject, promise }; };
const tick = () => new Promise(resolve => setImmediate(resolve));
const result = id => ({ request_id: id, bet: 30, status: 'lost', moves: 8, total_clears: 2, best_combo: 1 });
let calls = [];
record = async payload => { calls.push(payload.request_id); throw Error('offline'); };
queueDemoResult(result('one'));
await assert.rejects(flushDemoHistory(), /offline/);
assert.equal(entries.size, 1, 'failed synchronization keeps the result for a later visit');
record = async payload => { calls.push(payload.request_id); return { saved: true, round_id: payload.request_id }; };
await flushDemoHistory();
assert.deepEqual(calls, ['one', 'one'], 'retry keeps the same match identifier');
assert.equal(entries.size, 0);

queueDemoResult(result('pending-admin'));
user = { id: 'player' };
calls = [];
await flushDemoHistory();
assert.equal(calls.length, 0, 'another account cannot submit the previous admin history');
assert.equal(entries.size, 1);
user = { id: 'admin-one' };
await flushDemoHistory();
assert.equal(entries.size, 0);

const saving = deferred();
calls = [];
record = async payload => { calls.push(payload.request_id); if (payload.request_id === 'first') await saving.promise; return { saved: true, round_id: payload.request_id }; };
queueDemoResult(result('first'));
const firstFlush = flushDemoHistory();
queueDemoResult(result('second'));
const secondFlush = flushDemoHistory();
saving.resolve();
await Promise.all([firstFlush, secondFlush]);
assert.deepEqual(calls, ['first', 'second'], 'concurrent refreshes do not duplicate requests or lose newly queued results');
assert.equal(entries.size, 0);

const lobbyModule = new vm.SourceTextModule(await readFile(new URL('../src/scenes/LobbyScene.js', import.meta.url), 'utf8'), { context });
await lobbyModule.link(specifier => {
  if (specifier === '../services/api.js') return apiModule;
  if (specifier === '../services/demoHistory.js') return history;
  if (specifier === 'phaser') return synthetic({ default: { Scene: class {}, Scenes: { Events: { SHUTDOWN: 'shutdown' } } } });
  if (specifier === '../config.js') return synthetic({ W: 390, H: 844, state });
  if (specifier === '../brand.js') return synthetic({ BRAND: {} });
  throw Error(specifier);
});
await lobbyModule.evaluate();
const Lobby = lobbyModule.namespace.default;
const lobby = new Lobby();
lobby.init();
lobby.root = { remove: noop };
let renders = 0;
lobby._render = () => renders++;
lobby.scene = { start: noop };
const snapshot = (balance, count = 0) => ({ user, balance, demo_mode: false, history: count ? [{ round_id: 'synced', mult: 2.8, demo_mode: true, won: true, payout: 54 }] : [] });
const old = deferred(), latest = deferred();
const requests = [old, latest];
fetch = () => requests.shift().promise;
const oldLoad = lobby._loadLobby();
await tick();
const latestLoad = lobby._loadLobby();
await tick();
latest.resolve(snapshot(200, 1));
await latestLoad;
old.resolve(snapshot(100));
await oldLoad;
assert.equal(state.balance, 200, 'late response cannot replace newer account data');
assert.equal(lobby.snapshot.history.length, 1);
assert.equal(renders, 1);

let fetches = 0;
fetch = async () => { fetches++; return snapshot(200, 1); };
lobby.modal = 'deposit';
await lobby._loadLobby({ background: true });
assert.equal(fetches, 0, 'automatic refresh does not interrupt payment forms');
lobby.modal = null;
document.hidden = true;
await lobby._loadLobby({ background: true });
assert.equal(fetches, 0, 'hidden pages do not poll');
document.hidden = false;
await lobby._loadLobby({ background: true });
assert.equal(fetches, 1);
assert.equal(renders, 1, 'unchanged background snapshots do not redraw the lobby');
const openingForm = deferred();
fetch = () => openingForm.promise;
const formLoad = lobby._loadLobby({ background: true });
await tick();
lobby.modal = 'deposit';
openingForm.resolve(snapshot(999));
await formLoad;
assert.equal(state.balance, 200, 'refresh started before opening a payment form cannot replace its data');
assert.equal(renders, 1);
lobby.modal = null;
fetch = async () => { throw Error('temporary failure'); };
await lobby._loadLobby({ background: true });
assert.equal(lobby.snapshot.history.length, 1, 'temporary failures retain the confirmed history');
const closing = deferred();
fetch = () => closing.promise;
const closingLoad = lobby._loadLobby();
await tick();
lobby._cleanup();
closing.resolve(snapshot(999));
await closingLoad;
assert.equal(state.balance, 200, 'closed lobby ignores unfinished requests');

const accountLobby = new Lobby();
accountLobby.init();
accountLobby.root = { remove: noop };
accountLobby._render = noop;
fetch = async () => ({ ...snapshot(100), demo_mode: true });
await accountLobby._loadLobby();
assert.equal(state.balance, 100, 'lobby displays the confirmed admin demo balance');
assert.equal(state.demoMode, true);
fetch = async () => snapshot(37);
await accountLobby._loadLobby();
assert.equal(state.balance, 37, 'switching to a player restores the real balance');
assert.equal(state.demoMode, false, 'demo privileges do not leak into a player account');
accountLobby._cleanup();

const lifecycle = new Lobby();
lifecycle.init();
lifecycle._drawBackground = lifecycle._renderLoading = noop;
lifecycle._mountLobby = () => { lifecycle.root = { remove: noop }; };
let refreshes = 0, timerRemoved = false, timer;
lifecycle._loadLobby = () => refreshes++;
lifecycle.time = { addEvent: options => { timer = options; return { remove: () => { timerRemoved = true; } }; } };
lifecycle.events = { once: noop };
lifecycle.create();
assert.equal(timer.delay, 15000);
listeners.get('focus')();
listeners.get('visibilitychange')();
timer.callback();
assert.equal(refreshes, 4, 'entry, focus, visibility and periodic checks refresh account history');
lifecycle._cleanup();
assert.equal(timerRemoved, true);
assert.equal(listeners.size, 0);
console.log('History: durable demo retry, account isolation, refresh ordering and lifecycle OK');
